version: "3.9"
services:
  es:
    build: docker/es
    image: es:latest
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    container_name: elasticsearch
    volumes:
      - ./compose-root/data:/usr/share/elasticsearch/data
      - ./compose-root/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9900:9900
    healthcheck:
      test: wget -qO-  http://localhost:9900
      interval: 3s
      timeout: 5s
      retries: 60

  index-bot:
    build: .
    depends_on:
      - es
    image: index-bot:lastest
    container_name: index-bot
    volumes:
      - ./compose-root/log:/opt/index-bot/log
      - ./compose-root/data:/opt/index-bot/data
      - ./compose-root/lang:/opt/index-bot/lang
      - ./compose-root/application.yaml:/opt/index-bot/application.yaml