version: "3.9"
services:
  es:
    container_name: elasticsearch

    image: es:latest
    build: docker/es

    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    
    volumes:
      - ./compose-root/data:/usr/share/elasticsearch/data
      - ./compose-root/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

    healthcheck:
      test: wget -qO-  http://localhost:9900
      interval: 3s
      timeout: 5s
      retries: 60

  index-bot:

    # command: wget -qO-  http://es:9900
    container_name: index-bot

    image: index-bot:lastest
    build: .

    depends_on:
      - es

    # links:
    #   - es

    volumes:
      - ./compose-root/log:/opt/index-bot/log
      - ./compose-root/data:/opt/index-bot/data
      - ./compose-root/lang:/opt/index-bot/lang
      - ./compose-root/application.yaml:/opt/index-bot/application.yaml